export const GET_ERRORS = 'GET_ERRORS';
export const GET_DEPARTMENTS = 'GET_DEPARTMENTS';
export const GET_DEPARTMENT = 'GET_DEPARTMENT';
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';
export const CREATE_DEPARTMENT = 'CREATE_DEPARTMENT';
